flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.3.1.1
- MonadCatchIO-transformers-0.3.1.3
- MonadRandom-0.4.2.2
- SHA-1.6.4.2
- StateVar-1.1.0.3
- adjunctions-4.3
- aeson-0.10.0.0
- async-2.0.2
- attoparsec-0.13.0.1
- attoparsec-enumerator-0.3.4
- base-orphans-0.5.0
- base64-bytestring-1.0.0.1
- bifunctors-5.2
- blaze-builder-0.4.0.1
- blaze-builder-enumerator-0.2.1.0
- blaze-html-0.8.1.1
- bytes-0.15.2
- blaze-markup-0.7.0.3
- byteable-0.1.1
- bytestring-builder-0.10.6.0.0
- bytestring-mmap-0.2.2
- case-insensitive-1.2.0.5
- cereal-0.5.1.0
- cipher-aes-0.2.11
- clientsession-0.9.1.1
- comonad-4.2.7.2
- configurator-0.3.0.0
- contravariant-1.4
- cprng-aes-0.6.1
- crypto-api-0.13.2
- crypto-cipher-types-0.0.9
- crypto-random-0.0.9
- cryptohash-0.11.6
- directory-tree-0.12.0
- distributive-0.5.0.2
- dlist-0.7.1.2
- either-4.4.1
- engine-io-1.2.11
- engine-io-snap-1.0.3
- entropy-0.3.7
- enumerator-0.4.20
- exceptions-0.8.2.1
- extensible-exceptions-0.1.1.4
- free-4.12.4
- hashable-1.2.4.0
- heist-0.14.1.1
- kan-extensions-5.0.1
- lens-4.13.1
- logict-0.6.0.2
- map-syntax-0.2
- memory-0.11
- linear-1.20.4
- hspec-2.2.2
- QuickCheck-2.8.2
- hspec-core-2.2.2
- hspec-discover-2.2.2
- hspec-expectations-0.7.2
- ansi-terminal-0.6.2.3
- quickcheck-io-0.1.2
- tf-random-0.5
- mmorph-1.0.5
- monad-control-1.0.0.2
- monad-loops-0.4.3
- monads-tf-0.1.0.2
- mtl-2.2.1
- mwc-random-0.13.3.2
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.1.0
- parsec-3.1.9
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- pwstore-fast-2.4.4
- random-1.1
- reflection-2.1.1.1
- regex-base-0.93.2
- regex-posix-0.95.2
- scientific-0.3.4.4
- securemem-0.1.9
- semigroupoids-5.0.1
- semigroups-0.18.0.1
- setenv-0.1.1.3
- skein-1.0.9.4
- snap-0.14.0.6
- snap-core-0.9.8.0
- snap-cors-1.2.9
- snap-server-0.9.5.1
- socket-io-1.3.4
- stm-2.4.4.1
- stm-delay-0.1.1.1
- streaming-commons-0.1.15
- syb-0.6
- tagged-0.8.2
- text-1.2.2.0
- time-locale-compat-0.1.1.1
- transformers-0.4.3.0
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.1.4
- unordered-containers-0.2.6.0
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- void-0.7.1
- websockets-0.9.6.1
- websockets-snap-0.9.2.0
- xmlhtml-0.2.3.4
- zlib-0.6.1.1
- zlib-bindings-0.1.1.5
- zlib-enum-0.2.3.1
resolver: ghc-7.10.3
