flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- QuickCheck-2.8.2
- aeson-0.10.0.0
- async-2.0.2
- engine-io-1.2.11
- engine-io-snap-1.0.3
- kan-extensions-5.0.1
- lens-4.13.1
- monad-control-1.0.0.2
- reactive-banana-1.1.0.0
- snap-cors-1.2.9
- text-1.2.2.0
- transformers-0.4.3.0
- transformers-compat-0.5.1.4
- unordered-containers-0.2.6.0
resolver: lts-5.0
