flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- KdTree-0.2.1
- engine-io-snap-1.0.3
- pqueue-1.3.1
- reactive-banana-1.1.0.0
- snap-cors-1.2.9
- text-1.2.2.1
resolver: nightly-2016-03-31
